name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt

    - name: Build
      run: cargo build --verbose --release

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release-artifacts
        path: ./target/release/pQ
