name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v2
      with:
        toolchain: stable
        components: clippy, rustfmt

    - name: Build
      run: cargo build --verbose --release

    - name: Create Release
      id: create_release
      run: |
        gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
        gh release create "v${GITHUB_RUN_NUMBER}" ./target/release/pQ --title "Release v${GITHUB_RUN_NUMBER}" --notes "Release v${GITHUB_RUN_NUMBER}"

    - name: Upload Release Asset
      run: |
        gh release upload "v${GITHUB_RUN_NUMBER}" ./target/release/pQ --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
