name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt

    - name: Build
      run: cargo build --verbose --release

    - name: Install GitHub CLI
      run: sudo apt-get install gh

    - name: Authenticate with GitHub CLI
      run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

    - name: Create Release
      id: create_release
      run: gh release create "v${{ github.run_number }}" ./target/release/pQ --title "Release v${{ github.run_number }}" --notes "Release v${{ github.run_number }}"

    - name: Upload Release Asset
      run: gh release upload "v${{ github.run_number }}" ./target/release/pQ --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
